### ISSUE TITLE
Sacrificio de monstruos

### ISSUE THREAD

**Issue by manudelca** [MatiasMdelP/Al-Go-Oh#2]
Estuve pensando en como hacer lo de los sacrificios en monstruos según las correcciones del tp.
La idea sería hacer los cambios en el método de agregarMonstruo de Campo. El código sería:

```java

	public void agregarMonstruo(Monstruo monstruo) {

		for(Monstruo monstruoActual : monstruos) {
			try {
				
				monstruo.hacerSacrificio(monstruoActual);
				break;
			
			} catch(MonstruoEnElCementerioException excepcion) {
				
				continue;
				
			}
		};
		monstruos.add(monstruo);
	}
```
Donde el método de hacerSacrificio:

```java
	public void hacerSacrificio(Monstruo monstruo) throws MonstruoEnElCementerioException {
		if( this.necesitaSacrificios() ) {
			monstruo.mandarAlCementerio();
		}
	}
```

Y el metodo de necesitaSacrificios:

```java
	public boolean necesitaSacrificios() {
		return estrellas > 4;
	}

```

La idea es que se recorra la lista de monstruos hasta encontrar algún monstruo capaz de ser sacrificado y mandarlo al cementerio. En ese momento, el recorrido se para. Si se trata de mandar al cementerio a un monstruo muerto, se captura la excepcion y se sigue adelante.

Como veran, tiene fallas todavía:
1. No puede hacer el sacrificio de dos monstruos.
2. Si no hay ningún monstruo para sacrificar (ya sea porque la lista esta vacía o porque todos los monstruos estan en el cementerio), se agrega igualmente el monstruo a la lista cuando no debería. Ahora que lo pienso, se podría agregar otro método de campo que recorra la lista y avise si hay por lo menos un monstruo vivo. 

La otra solución que se podría hacer es que directamente se le pase la lista completa de todos los monstruos del campo al monstruo que tiene que hacer los sacrificios y que la itere él mismo. Eso seguramente facilite la resolución del problema del sacrificio de dos monstruos pero no sé que tan objetoso es respecto de esta solución. 

Lo planteo como un primer acercamiento al problema.

**Comment by romeromaxi** [comment]
Yo también estaba pensando en sacar el hacerSacrificio de Monstruo para pasarlo a la clase Campo. El motivo es que viendo las cartas de la consigna, hay una que para invocarla, necesita que sacrificara un determinado tipo de Carta (el dragón de ojos azules).  
Y para poder hacerlo lo único que se me ocurrió fue lo último que dijiste: "La otra solución que se podría hacer es que directamente se le pase la lista completa de todos los monstruos del campo al monstruo que tiene que hacer los sacrificios y que la itere él mismo." y con el mismo problema.

Lo otro sino es que cada Carta tenga como es su 'invocación', y también le pasaría una lista de los monstruos que hay en el campo de juego.

**Comment by romeromaxi** [comment]
Me parece que vamos a necesitar lo de la 'Invocación' porque hay varios que requieren hacer sacrificios específicos o tienen Efectos sobre otras cosas cuando se los invoca.

**Comment by manudelca** [comment]
Me gusta eso de la Invocacion. Cómo y cuando los inicializarías? También me parece que si hacemos lo de pasarle la lista de monstruos al Monstruo, tendríamos que eliminar a la clase Campo porque como había dicho el corrector, nos queda sin funcionalidad y es solamente una base de datos. (Pasamos la lista de todos los monstruos a que sea un atributo de Jugador)

**Comment by romeromaxi** [comment]
Lo que se me había ocurrido es que la Carta tenga un atributo Invocacion que lo pasas por el constructor (como lo que estamos haciendo con Efecto). Y llamarías al método invocar de Carta, que delega al tipo Invocar, cuando queres pasar una Carta de la Mano a la ZonaMonstruo, o a la zona que corresponda.
